# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32ebfcdf0dbde0cbb9a9b52ab2b7eab1b789d8661625417c50d25c64163104fe3851d556798a0a498824bc650c9675926389ad3ec6391c8366a85ed26558df36

test:
  secret_key_base: 0c1ce0efe4cd646353037e9fe15c91e1d3c6bf80ad8a3e024d5ac044f524be43ad9e92f7325bd904ee5678f0aa502841b8cfed16d91883aef9bc07ffd57493ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
